name: Merge Request

# 触发条件：在 push 到 master 分支后
on:
  pull_request:
    branches:
      - master

# 任务
jobs:
  merge-request:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # 安装依赖
      - name: Install
        run: yarn

      # 单元测试
      - name: Test
        run: npm test

      # 代码lint
      - name: Lint
        run: npm run lint
